### PR TITLE
Fix modications typo

### PR DESCRIPTION
**Pull request by wouter-muller**

### CODE REVIEW

**Comment by wouter-muller** [comment]
@braver Why was this closed? Seems like a legit change...

**Comment by wouter-muller** [comment]
And the typo is still present in your README.md

**Comment by braver** [comment]
Sure, getting around to the explanation. I'm updating all readme's across our linters. Thanks for keeping an eye out though!

**Comment by wouter-muller** [comment]
Alright! :+1:

**Pull request closed without merging**
